trigger:
- master

resources:
  - repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  containerRegistry: 'rpaazuredevcr.azurecr.io'
  imagerepository: 'rpaazure'
  tag: $(Build.SourceVersion)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Dotnet Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(solution)'

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(containerRegistry)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    containerRegistry: 'RPAAzure-ACR-Service-Connection'
    tags: |
      $(tag)
      latest
  
- script: |
    
    sudo add-apt-repository ppa:rmescandon/yq
    sudo apt-get install yq

    git config --global credential.helper '!f() { echo "username=$1"; echo "password=$2"; }; f $(system.accesstoken) $(GITHUBPAT)'
    git config --global user.email "abhishekb@esspl.com"
    git config --global user.name "Abhishek"

    git clone https://github.com/abhishekess/RPAAzure-Infrastructure.git
    
    cd RPAAzure-Infrastructure/overlays/dev
    
    yq e -i '.images.[] |= {select(.name == "$(containerRegistry)/$(imagerepository)") |= .newTag = "$(tag)"}' kustomization.yaml
    
    cd ../../
    
    git add .
    git commit -m "update dev $(Build.Repository.Name)"
    git push

  displayName: 'Deploy dev'