parameters:
  - name: AcrPassword
    displayName: AcrPassword
    type: string
    default: ''

trigger:
- master

resources:
  - repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Dotnet Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(solution)'

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: rpaazure
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    containerRegistry: 'RPAAzure-ACR-Service-Connection'
    arguments: '--registry-login-server rpaazuredevcr.azurecr.io --registry-username rpaazuredevcr --registry-password ${{ parameters.AcrPassword }}'
    tags: |
      $(Build.SourceVersion)
      latest
  